export const TRANSACTION_COLUMN_DEFINITIONS = [
  {
    id: 'date',
    label: 'Date',
    minWidth: 132,
    defaultWidth: 132,
    sortable: true,
    dataType: 'date',
    defaultFormat: 'DD/MM/YY',
    formatOptions: ['DD/MM/YY', 'MM/DD/YY', 'YYYY-MM-DD'],
  },
  {
    id: 'type',
    label: 'Type',
    minWidth: 132,
    defaultWidth: 132,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'account',
    label: 'Account',
    minWidth: 182,
    defaultWidth: 182,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'shop',
    label: 'Shop',
    minWidth: 180,
    defaultWidth: 196,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'notes',
    label: 'Notes',
    minWidth: 240,
    defaultWidth: 260,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'amount',
    label: 'Amount',
    minWidth: 150,
    defaultWidth: 160,
    align: 'right',
    sortable: true,
    dataType: 'number',
  },
  {
    id: 'percentBack',
    label: '% Back',
    minWidth: 120,
    defaultWidth: 132,
    align: 'right',
    sortable: true,
    dataType: 'number',
  },
  {
    id: 'fixedBack',
    label: 'Fix Back',
    minWidth: 140,
    defaultWidth: 150,
    align: 'right',
    sortable: true,
    dataType: 'number',
  },
  {
    id: 'totalBack',
    label: 'Total Back',
    minWidth: 170,
    defaultWidth: 190,
    align: 'right',
    sortable: true,
    dataType: 'number',
  },
  {
    id: 'finalPrice',
    label: 'Final Price',
    minWidth: 160,
    defaultWidth: 180,
    align: 'right',
    sortable: true,
    dataType: 'number',
  },
  {
    id: 'debtTag',
    label: 'Debt Tag',
    minWidth: 160,
    defaultWidth: 170,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'cycleTag',
    label: 'Cycle Tag',
    minWidth: 150,
    defaultWidth: 160,
    defaultVisible: false,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'category',
    label: 'Category',
    minWidth: 150,
    defaultWidth: 160,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'linkedTxn',
    label: 'Linked TXN',
    minWidth: 160,
    defaultWidth: 176,
    defaultVisible: false,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'owner',
    label: 'Owner',
    minWidth: 130,
    defaultWidth: 140,
    sortable: true,
    dataType: 'string',
  },
  {
    id: 'id',
    label: 'ID',
    minWidth: 180,
    defaultWidth: 200,
    defaultVisible: false,
    sortable: true,
    dataType: 'string',
  },
];

export const MANDATORY_TRANSACTION_COLUMNS = ['date', 'type', 'amount'];

export const DEFAULT_TRANSACTION_SORT = [
  { id: 'date', direction: 'desc' },
];

export function getDefaultColumnState() {
  return TRANSACTION_COLUMN_DEFINITIONS.map((definition, index) => ({
    id: definition.id,
    width: definition.defaultWidth,
    visible: definition.defaultVisible !== false,
    order: index,
    format: definition.defaultFormat,
  }));
}
