const MOCK_SOURCE = [
  {
    id: 'txn-0001',
    date: '2025-02-12',
    type: 'Expense',
    account: 'Primary Checking',
    shop: 'Aurora Grocers',
    notes: 'Weekly grocery run',
    amount: 184.67,
    percentBack: 4,
    fixedBack: 6.5,
    debtTag: 'Household',
    cycleTag: 'Cycle 02',
    category: 'Groceries',
    linkedTxn: 'LNK-2387',
    owner: 'Rena',
  },
  {
    id: 'txn-0002',
    date: '2025-02-13',
    type: 'Income',
    account: 'Rewards Wallet',
    shop: 'Cashback Flow',
    notes: 'February cashback release',
    amount: 320.0,
    percentBack: 0,
    fixedBack: 0,
    debtTag: 'Rebate',
    cycleTag: 'Cycle 02',
    category: 'Cashback',
    linkedTxn: 'LNK-1803',
    owner: 'Iris',
  },
  {
    id: 'txn-0003',
    date: '2025-02-16',
    type: 'Expense',
    account: 'Primary Checking',
    shop: 'Metro Fuel',
    notes: 'Fuel top-up',
    amount: 76.12,
    percentBack: 2,
    fixedBack: 0,
    debtTag: 'Auto',
    cycleTag: 'Cycle 02',
    category: 'Transport',
    linkedTxn: 'LNK-2387',
    owner: 'Rena',
  },
  {
    id: 'txn-0004',
    date: '2025-02-18',
    type: 'Expense',
    account: 'Corporate Card',
    shop: 'Cloud Nine Cafe',
    notes: 'Client meeting brunch',
    amount: 142.35,
    percentBack: 5,
    fixedBack: 8,
    debtTag: 'Client - Juno',
    cycleTag: 'Cycle 02',
    category: 'Hospitality',
    linkedTxn: 'LNK-2012',
    owner: 'Noah',
  },
  {
    id: 'txn-0005',
    date: '2025-02-21',
    type: 'Expense',
    account: 'Primary Checking',
    shop: 'HealthFirst Pharmacy',
    notes: 'Monthly prescriptions',
    amount: 92.85,
    percentBack: 3,
    fixedBack: 4,
    debtTag: 'Healthcare',
    cycleTag: 'Cycle 02',
    category: 'Health',
    linkedTxn: 'LNK-1099',
    owner: 'Iris',
  },
  {
    id: 'txn-0006',
    date: '2025-02-23',
    type: 'Expense',
    account: 'Corporate Card',
    shop: 'Skyline Suites',
    notes: 'Conference travel lodging',
    amount: 612.5,
    percentBack: 6,
    fixedBack: 12.5,
    debtTag: 'Travel - Summit',
    cycleTag: 'Cycle 02',
    category: 'Travel',
    linkedTxn: 'LNK-3011',
    owner: 'Noah',
  },
  {
    id: 'txn-0007',
    date: '2025-02-24',
    type: 'Expense',
    account: 'Cash Reserve',
    shop: 'BrightLine Utilities',
    notes: 'Electric bill',
    amount: 128.0,
    percentBack: 1,
    fixedBack: 0,
    debtTag: 'Utilities',
    cycleTag: 'Cycle 02',
    category: 'Utilities',
    linkedTxn: 'LNK-1144',
    owner: 'Rena',
  },
  {
    id: 'txn-0008',
    date: '2025-03-01',
    type: 'Expense',
    account: 'Primary Checking',
    shop: 'Orbit Electronics',
    notes: 'Monitor upgrade',
    amount: 412.0,
    percentBack: 5,
    fixedBack: 10,
    debtTag: 'Workspace',
    cycleTag: 'Cycle 03',
    category: 'Office',
    linkedTxn: 'LNK-2791',
    owner: 'Rena',
  },
  {
    id: 'txn-0009',
    date: '2025-03-03',
    type: 'Income',
    account: 'Reimbursements',
    shop: 'Debt Movements',
    notes: 'Debt repayment - Summit',
    amount: 450.0,
    percentBack: 0,
    fixedBack: 0,
    debtTag: 'Travel - Summit',
    cycleTag: 'Cycle 03',
    category: 'Debt',
    linkedTxn: 'LNK-3011',
    owner: 'Noah',
  },
  {
    id: 'txn-0010',
    date: '2025-03-06',
    type: 'Expense',
    account: 'Subscription Wallet',
    shop: 'SaaSify',
    notes: 'Quarterly CRM renewal',
    amount: 899.99,
    percentBack: 7,
    fixedBack: 18,
    debtTag: 'Operations',
    cycleTag: 'Cycle 03',
    category: 'Subscription',
    linkedTxn: 'LNK-3344',
    owner: 'Iris',
  },
  {
    id: 'txn-0011',
    date: '2025-03-08',
    type: 'Expense',
    account: 'Batch Input',
    shop: 'Market Collective',
    notes: 'Bulk inventory purchase',
    amount: 1275.45,
    percentBack: 5,
    fixedBack: 22.5,
    debtTag: 'Inventory',
    cycleTag: 'Cycle 03',
    category: 'Inventory',
    linkedTxn: 'LNK-4588',
    owner: 'Noah',
  },
  {
    id: 'txn-0012',
    date: '2025-03-09',
    type: 'Expense',
    account: 'Primary Checking',
    shop: 'City Fitness',
    notes: 'Team wellness stipend',
    amount: 210.0,
    percentBack: 4,
    fixedBack: 6,
    debtTag: 'HR',
    cycleTag: 'Cycle 03',
    category: 'Benefits',
    linkedTxn: 'LNK-4588',
    owner: 'Iris',
  },
];

function enrichTransaction(txn) {
  const totalBack = Number(
    ((txn.amount * (txn.percentBack ?? 0)) / 100 + (txn.fixedBack ?? 0)).toFixed(2),
  );
  const finalPrice = Number((txn.amount - totalBack).toFixed(2));

  return {
    ...txn,
    totalBack,
    finalPrice,
  };
}

export async function fetchMockTransactions() {
  await new Promise((resolve) => {
    setTimeout(resolve, 120);
  });

  return MOCK_SOURCE.map(enrichTransaction);
}

